# Generated by Django 6.0.4 on 2026-04-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_name', models.CharField(max_length=100)),
                ('match_type', models.CharField(choices=[('Scrim', 'Scrim'), ('Official', 'Official')], default='Scrim', max_length=20)),
                ('date', models.DateTimeField()),
                ('score_team', models.PositiveBigIntegerField(default=0)),
                ('score_opponent', models.PositiveBigIntegerField(default=0)),
                ('result', models.CharField(choices=[('Win', 'Win'), ('Loss', 'Loss')], default='Loss', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
