# Generated by Django 6.0.4 on 2026-04-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
    ]
