# Generated by Django 6.0.4 on 2026-04-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
        ('players', '0002_initial'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playermatchstats',
            unique_together={('player', 'match')},
        ),
    ]
