# Generated by Django 6.0.4 on 2026-04-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
        ('players', '0002_initial'),
        ('stats', '0002_alter_playermatchstats_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playermatchstats',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='players.player'),
        ),
        migrations.AlterUniqueTogether(
            name='playermatchstats',
            unique_together={('player', 'match', 'map_name')},
        ),
    ]
