# Generated by Django 6.0.4 on 2026-05-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_playermatchstats_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstats',
            name='agent_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
