# Generated by Django 6.0.4 on 2026-05-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='riot_game_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='riot_tag_line',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
